version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres # Should be the same as your .env DB
      - POSTGRES_USER=postgres # Should be the same as your .env User
      - POSTGRES_PASSWORD=root # Should be the same as your .env Password
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db