name: Backend CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install install pytest
          pip install -r requirements.txt

      - name: Run lint
        run: |
          pycodestyle . --max-line-length=127
          echo "If the above fails please run `autopep8 -i -r -v --max-line-length 127 backend/` (see root npm package.json)"

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test

