name: Frontend CI

on:
  pull_request:
    branches:
    - main
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install frontend dependency
      run: |
        cd frontend
        npm install
        sudo npm install eslint -g

    - name: Run frontend lint
      run: |
        cd frontend
        eslint . --max-warnings 0
